export const countryOptions = [
  { key: "ca", value: "ca", flag: "ca", text: "Canada" },
  {
    key: "us",
    value: "us",
    flag: "us",
    text: "United States",
    disabled: true,
  },
  { key: "af", value: "af", flag: "af", text: "Afghanistan", disabled: true },
  {
    key: "ax",
    value: "ax",
    flag: "ax",
    text: "Aland Islands",
    disabled: true,
  },
  { key: "al", value: "al", flag: "al", text: "Albania", disabled: true },
  { key: "dz", value: "dz", flag: "dz", text: "Algeria", disabled: true },
  {
    key: "as",
    value: "as",
    flag: "as",
    text: "American Samoa",
    disabled: true,
  },
  { key: "ad", value: "ad", flag: "ad", text: "Andorra", disabled: true },
  { key: "ao", value: "ao", flag: "ao", text: "Angola", disabled: true },
  { key: "ai", value: "ai", flag: "ai", text: "Anguilla", disabled: true },
  { key: "ag", value: "ag", flag: "ag", text: "Antigua", disabled: true },
  { key: "ar", value: "ar", flag: "ar", text: "Argentina", disabled: true },
  { key: "am", value: "am", flag: "am", text: "Armenia", disabled: true },
  { key: "aw", value: "aw", flag: "aw", text: "Aruba", disabled: true },
  { key: "au", value: "au", flag: "au", text: "Australia", disabled: true },
  { key: "at", value: "at", flag: "at", text: "Austria", disabled: true },
  { key: "az", value: "az", flag: "az", text: "Azerbaijan", disabled: true },
  { key: "bs", value: "bs", flag: "bs", text: "Bahamas", disabled: true },
  { key: "bh", value: "bh", flag: "bh", text: "Bahrain", disabled: true },
  { key: "bd", value: "bd", flag: "bd", text: "Bangladesh", disabled: true },
  { key: "bb", value: "bb", flag: "bb", text: "Barbados", disabled: true },
  { key: "by", value: "by", flag: "by", text: "Belarus", disabled: true },
  { key: "be", value: "be", flag: "be", text: "Belgium", disabled: true },
  { key: "bz", value: "bz", flag: "bz", text: "Belize", disabled: true },
];
