export const profile = {
  firstName: "",
  lastName: "",
  country: "",
  countryCode: "",
  currency: "CAD",
  earnAmount: 0,
  spendAmount: 0,
  purchased: {},
  goalYear: 0,
  goalJob: {
    title: "",
    medianSalary: "",
    topSalary: "",
    educationPeriod: "",
    hasDegree: false,
    degree: "",
  },
  tutorial1: false,
  tutorial2: false,
};
