//https://www.quicken.com/blog/budget-categories/

//Housing (25~35%)
export const houseBuy = [
  {
    type: "Buy",
    name: "Condo in downtown area",
    minPrice: 500000,
    maxPrice: 1000000,
    quantity: 0,
  },
  {
    type: "Buy",
    name: "Single-family house in suburban area",
    minPrice: 700000,
    maxPrice: 2000000,
    quantity: 0,
  },
  {
    type: "Buy",
    name: "Luxury townhouse in exclusive community",
    minPrice: 2000000,
    maxPrice: 5000000,
    quantity: 0,
  },
  {
    type: "Buy",
    name: "Waterfront mansion in coastal area",
    minPrice: 10000000,
    maxPrice: 25000000,
    quantity: 0,
  },
  {
    type: "Buy",
    name: "High-rise penthouse in city center",
    minPrice: 5000000,
    maxPrice: 10000000,
    quantity: 0,
  },
  {
    type: "Buy",
    name: "Large country estate with acreage",
    minPrice: 2000000,
    maxPrice: 10000000,
    quantity: 0,
  },
  {
    type: "Buy",
    name: "Ultra-luxury private island",
    minPrice: 50000000,
    maxPrice: 100000000,
    quantity: 0,
  },
];

export const houseRent = [
  {
    type: "Rent",
    name: "Small apartment in urban area",
    minPrice: 500,
    maxPrice: 2000,
    quantity: 0,
  },
  {
    type: "Rent",
    name: "Luxury apartment in high-end neighborhood",
    minPrice: 5000,
    maxPrice: 15000,
    quantity: 0,
  },
  {
    type: "Rent",
    name: "Luxury villa in resort area",
    minPrice: 15000,
    maxPrice: 25000,
    quantity: 0,
  },
];

//Utilities (5~10%)
export const utilities = [
  {
    type: "Util",
    name: "Electricity",
    minPrice: 50,
    maxPrice: 150,
    quantity: 0,
  },
  { type: "Util", name: "Water", minPrice: 30, maxPrice: 100, quantity: 0 },
  { type: "Util", name: "Gas", minPrice: 20, maxPrice: 100, quantity: 0 },
  { type: "Util", name: "Internet", minPrice: 50, maxPrice: 100, quantity: 0 },
  { type: "Util", name: "Cable TV", minPrice: 30, maxPrice: 100, quantity: 0 },
];

//Transportation (10~15%)
export const transportation = [
  {
    name: "Subway/Transit pass",
    minPrice: 100,
    maxPrice: 150,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Uber/Lyft ride",
    minPrice: 10,
    maxPrice: 250,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Domestic flight",
    minPrice: 100,
    maxPrice: 500,
    unit: "once",
    quantity: 0,
  },
  {
    name: "International flight",
    minPrice: 300,
    maxPrice: 2500,
    unit: "once",
    quantity: 0,
  },
  { name: "Car Gas", minPrice: 10, maxPrice: 200, unit: "once", quantity: 0 },
];

//Food (10~15%)
export const food = [
  { name: "Grocery", minPrice: 5, maxPrice: 300, quantity: 0 },
  { name: "Takeout", minPrice: 10, maxPrice: 50, quantity: 0 },
  { name: "Delivery food", minPrice: 15, maxPrice: 50, quantity: 0 },
  { name: "Cheap restaurant", minPrice: 10, maxPrice: 20, quantity: 0 },
  { name: "Expensive restaurant", minPrice: 30, maxPrice: 200, quantity: 0 },
];

//Insurance (10~25%)
export const insurance = [
  { name: "Health insurance", minPrice: 100, maxPrice: 500, quantity: 0 },
  {
    name: "Homeowner's or renter's insurance",
    minPrice: 20,
    maxPrice: 100,
    quantity: 0,
  },
  {
    name: "Home warranties or protection plans",
    minPrice: 30,
    maxPrice: 100,
    quantity: 0,
  },
  { name: "Auto insurance", minPrice: 50, maxPrice: 200, quantity: 0 },
  { name: "Life insurance", minPrice: 20, maxPrice: 100, quantity: 0 },
  { name: "Disability insurance", minPrice: 20, maxPrice: 50, quantity: 0 },
];

//Healthcare (5~10%)
export const healthcare = [
  {
    name: "Specialty care (dermatologists, psychologists, etc.)",
    minPrice: 100,
    maxPrice: 500,
    quantity: 0,
  },
  { name: "Dental care", minPrice: 50, maxPrice: 300, quantity: 0 },
  { name: "Urgent care", minPrice: 100, maxPrice: 300, quantity: 0 },
  {
    name: "Prescriptions and OTC medications",
    minPrice: 10,
    maxPrice: 100,
    quantity: 0,
  },
  { name: "Supplements and vitamins", minPrice: 10, maxPrice: 50, quantity: 0 },
  {
    name: "Medical devices and supplies",
    minPrice: 20,
    maxPrice: 200,
    quantity: 0,
  },
];

//Investing (10~20%)
export const investing = [];

//PersonalSpending (5~10%)
export const personalItems = [
  { name: "Toothbrush", minPrice: 1, quantity: 0 },
  { name: "Pen", minPrice: 2, quantity: 0 },
  { name: "Notebook", minPrice: 3, quantity: 0 },
  { name: "T-shirt", minPrice: 10, quantity: 0 },
  { name: "Umbrella", minPrice: 15, quantity: 0 },
  { name: "Running shoes", minPrice: 50, quantity: 0 },
  { name: "Bluetooth speaker", minPrice: 60, quantity: 0 },
  { name: "Fitness tracker", minPrice: 70, quantity: 0 },
  { name: "Tablet", minPrice: 100, quantity: 0 },
  { name: "Slow cooker", minPrice: 150, quantity: 0 },
  { name: "Smartwatch", minPrice: 200, quantity: 0 },
  { name: "Digital camera", minPrice: 250, quantity: 0 },
  { name: "Wireless headphones", minPrice: 300, quantity: 0 },
  { name: "Smart thermostat", minPrice: 350, quantity: 0 },
  { name: "Robot vacuum", minPrice: 400, quantity: 0 },
  { name: "Drone", minPrice: 500, quantity: 0 },
  { name: "Electric guitar", minPrice: 600, quantity: 0 },
  { name: "Gaming console", minPrice: 700, quantity: 0 },
  { name: "Mountain bike", minPrice: 800, quantity: 0 },
  { name: "Home theater system", minPrice: 900, quantity: 0 },
  { name: "High-quality binoculars", minPrice: 1000, quantity: 0 },
  { name: "High-end laptop", minPrice: 1500, quantity: 0 },
  { name: "DSLR camera", minPrice: 2000, quantity: 0 },
  { name: "Diamond stud earrings", minPrice: 3000, quantity: 0 },
  { name: "Apple MacBook Pro", minPrice: 3500, quantity: 0 },
  { name: "Rolex watch", minPrice: 5000, quantity: 0 },
  { name: "Custom-built gaming PC", minPrice: 6000, quantity: 0 },
  { name: "4K Ultra HD TV", minPrice: 7000, quantity: 0 },
  { name: "Baby grand piano", minPrice: 10000, quantity: 0 },
  { name: "Designer handbag", minPrice: 12000, quantity: 0 },
  { name: "Luxury Swiss watch", minPrice: 15000, quantity: 0 },
  { name: "Designer wedding dress", minPrice: 20000, quantity: 0 },
  { name: "Luxury sports car", minPrice: 50000, quantity: 0 },
  { name: "Speedboat", minPrice: 75000, quantity: 0 },
  { name: "Personal submarine", minPrice: 100000, quantity: 0 },
  { name: "Tesla Model S", minPrice: 100000, quantity: 0 },
  { name: "Private jet membership", minPrice: 150000, quantity: 0 },
  { name: "Classic car restoration", minPrice: 200000, quantity: 0 },
  { name: "Sports memorabilia collection", minPrice: 250000, quantity: 0 },
  { name: "Luxury yacht rental", minPrice: 500000, quantity: 0 },
  { name: "Diamond engagement ring", minPrice: 1000000, quantity: 0 },
  { name: "Original artwork", minPrice: 2000000, quantity: 0 },
  { name: "Luxury real estate", minPrice: 3000000, quantity: 0 },
  { name: "Superyacht", minPrice: 50000000, quantity: 0 },
  { name: "Private island", minPrice: 100000000, quantity: 0 },
  { name: "Commercial airliner", minPrice: 200000000, quantity: 0 },
  { name: "Oil tanker", minPrice: 300000000, quantity: 0 },
  { name: "Cruise ship", minPrice: 500000000, quantity: 0 },
  { name: "Space tourism ticket", minPrice: 250000000, quantity: 0 },
  { name: "Nuclear submarine", minPrice: 2000000000, quantity: 0 },
];

export const personalServices = [
  {
    name: "Social media management services",
    minPrice: 100,
    maxPrice: 500,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Public relations services",
    minPrice: 1000,
    maxPrice: 10000,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Executive coaching services",
    minPrice: 500,
    maxPrice: 2000,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Yoga class",
    minPrice: 10,
    maxPrice: 30,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Cooking classes",
    min_price: 50,
    max_price: 200,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Art classes",
    min_price: 50,
    max_price: 200,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Gym Membership",
    min_price: 30,
    max_price: 300,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Meditation classes",
    min_price: 30,
    max_price: 200,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Music lessons",
    min_price: 50,
    max_price: 200,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Dance lessons",
    min_price: 100,
    max_price: 400,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Language lessons",
    min_price: 20,
    max_price: 100,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Netflix",
    minPrice: 8.99,
    maxPrice: 17.99,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Meal delivery service",
    minPrice: 8,
    maxPrice: 15,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Music streaming service",
    minPrice: 4.99,
    maxPrice: 14.99,
    unit: "monthly",
    quantity: 0,
  },
  { name: "Haircut", minPrice: 10, maxPrice: 100, unit: "once", quantity: 0 },
  { name: "Massage", minPrice: 50, maxPrice: 200, unit: "once", quantity: 0 },
  {
    name: "Personal training session",
    minPrice: 50,
    maxPrice: 150,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Nutrition consultation",
    minPrice: 100,
    maxPrice: 300,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "House cleaning",
    minPrice: 50,
    maxPrice: 200,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Landscaping",
    minPrice: 100,
    maxPrice: 500,
    unit: "monthly",
    quantity: 0,
  },
  {
    name: "Plumbing service",
    minPrice: 100,
    maxPrice: 300,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Electrical repair",
    minPrice: 50,
    maxPrice: 500,
    unit: "once",
    quantity: 0,
  },
  { name: "Car wash", minPrice: 10, maxPrice: 50, unit: "once", quantity: 0 },
  {
    name: "Car detailing",
    minPrice: 100,
    maxPrice: 300,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Pest control",
    minPrice: 100,
    maxPrice: 500,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Pet grooming",
    minPrice: 50,
    maxPrice: 150,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Dog walking",
    minPrice: 10,
    maxPrice: 50,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Tutoring services",
    minPrice: 20,
    maxPrice: 100,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Interior design consultation",
    minPrice: 100,
    maxPrice: 300,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Home organization services",
    minPrice: 50,
    maxPrice: 200,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Event planning services",
    minPrice: 500,
    maxPrice: 5000,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Wedding planning services",
    minPrice: 1000,
    maxPrice: 10000,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Photography services",
    minPrice: 100,
    maxPrice: 500,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Videography services",
    minPrice: 500,
    maxPrice: 2000,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Graphic design services",
    minPrice: 50,
    maxPrice: 500,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Website development services",
    minPrice: 500,
    maxPrice: 5000,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Legal services",
    minPrice: 100,
    maxPrice: 500,
    unit: "hourly",
    quantity: 0,
  },
  {
    name: "Accounting services",
    minPrice: 50,
    maxPrice: 500,
    unit: "hourly",
    quantity: 0,
  },
  {
    name: "Financial planning services",
    minPrice: 100,
    maxPrice: 500,
    unit: "hourly",
    quantity: 0,
  },
  {
    name: "Career counseling services",
    minPrice: 50,
    maxPrice: 200,
    unit: "hourly",
    quantity: 0,
  },
  {
    name: "Business coaching services",
    minPrice: 100,
    maxPrice: 500,
    unit: "hourly",
    quantity: 0,
  },
  {
    name: "Interpretation services",
    min_price: 50,
    max_price: 150,
    unit: "hourly",
    quantity: 0,
  },
  {
    name: "Tax preparation services",
    minPrice: 100,
    maxPrice: 500,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Home renovation services",
    min_price: 5000,
    max_price: 50000,
    unit: "once",
    quantity: 0,
  },
  {
    name: "Moving services",
    min_price: 500,
    max_price: 5000,
    unit: "once",
    quantity: 0,
  },
];

//Recreation (5~10%)
export const recreationActivities = [
  { name: "Movie tickets", minPrice: 10, maxPrice: 20, quantity: 0 },
  { name: "Concert tickets", minPrice: 50, maxPrice: 200, quantity: 0 },
  { name: "Sports events tickets", minPrice: 30, maxPrice: 200, quantity: 0 },
  { name: "Museum admission fees", minPrice: 10, maxPrice: 30, quantity: 0 },
  { name: "Theme park tickets", minPrice: 50, maxPrice: 150, quantity: 0 },
  {
    name: "Zoo or aquarium admission fees",
    minPrice: 10,
    maxPrice: 30,
    quantity: 0,
  },
  { name: "Scuba diving", minPrice: 100, maxPrice: 300, quantity: 0 },
  { name: "Skydiving", minPrice: 200, maxPrice: 500, quantity: 0 },
  { name: "Bungee jumping", minPrice: 50, maxPrice: 200, quantity: 0 },
  { name: "Jet skiing", minPrice: 50, maxPrice: 150, quantity: 0 },
  {
    name: "Kayaking or canoeing rentals",
    minPrice: 20,
    maxPrice: 50,
    quantity: 0,
  },
  { name: "Fishing gear rentals", minPrice: 20, maxPrice: 50, quantity: 0 },
  { name: "Horseback riding", minPrice: 30, maxPrice: 100, quantity: 0 },
  { name: "Zip-lining", minPrice: 50, maxPrice: 150, quantity: 0 },
  { name: "Rock climbing gym", minPrice: 20, maxPrice: 40, quantity: 0 },
  { name: "White water rafting", minPrice: 50, maxPrice: 150, quantity: 0 },
  { name: "Camping gear rentals", minPrice: 30, maxPrice: 100, quantity: 0 },
  { name: "Ski or snowboard rentals", minPrice: 30, maxPrice: 80, quantity: 0 },
  { name: "Ski lift tickets", minPrice: 50, maxPrice: 150, quantity: 0 },
  { name: "Snowmobile rentals", minPrice: 50, maxPrice: 150, quantity: 0 },
  { name: "Hot air balloon ride", minPrice: 100, maxPrice: 300, quantity: 0 },
];

export const recreationStays = [
  { name: "Budget hotel", minPrice: 50, maxPrice: 100, quantity: 0 },
  { name: "Mid-range hotel", minPrice: 100, maxPrice: 200, quantity: 0 },
  { name: "Luxury hotel", minPrice: 200, maxPrice: 500, quantity: 0 },
  { name: "Hostel", minPrice: 20, maxPrice: 50, quantity: 0 },
  { name: "Airbnb private room", minPrice: 30, maxPrice: 100, quantity: 0 },
  {
    name: "Airbnb entire apartment or house",
    minPrice: 50,
    maxPrice: 300,
    quantity: 0,
  },
  { name: "Motel", minPrice: 30, maxPrice: 80, quantity: 0 },
  { name: "Resort", minPrice: 150, maxPrice: 500, quantity: 0 },
  { name: "Camping or RV park", minPrice: 20, maxPrice: 50, quantity: 0 },
  { name: "Glamping", minPrice: 100, maxPrice: 300, quantity: 0 },
  { name: "Vacation rental", minPrice: 100, maxPrice: 500, quantity: 0 },
  { name: "Ski lodge", minPrice: 150, maxPrice: 500, quantity: 0 },
  {
    name: "Beachfront condo or apartment",
    minPrice: 100,
    maxPrice: 500,
    quantity: 0,
  },
  {
    name: "Treehouse or unique rental",
    minPrice: 50,
    maxPrice: 300,
    quantity: 0,
  },
];
