export const top20Currencies = [
  { code: "CAD", flag: "🇨🇦" },
  { code: "USD", flag: "🇺🇸" },
  { code: "EUR", flag: "🇪🇺" },
  { code: "JPY", flag: "🇯🇵" },
  { code: "GBP", flag: "🇬🇧" },
  { code: "AUD", flag: "🇦🇺" },
  { code: "CHF", flag: "🇨🇭" },
  { code: "CNY", flag: "🇨🇳" },
  { code: "HKD", flag: "🇭🇰" },
  { code: "NZD", flag: "🇳🇿" },
  { code: "SEK", flag: "🇸🇪" },
  { code: "KRW", flag: "🇰🇷" },
  { code: "SGD", flag: "🇸🇬" },
  { code: "NOK", flag: "🇳🇴" },
  { code: "MXN", flag: "🇲🇽" },
  { code: "INR", flag: "🇮🇳" },
  { code: "RUB", flag: "🇷🇺" },
  { code: "ZAR", flag: "🇿🇦" },
  { code: "TRY", flag: "🇹🇷" },
  { code: "BRL", flag: "🇧🇷" },
];
