export const top20Currencies = [
  { code: "CAD", flag: "🇨🇦", country: "Canada" },
  { code: "USD", flag: "🇺🇸", country: "United States" },
  { code: "EUR", flag: "🇪🇺", country: "European Union" },
  { code: "JPY", flag: "🇯🇵", country: "Japan" },
  // { code: "GBP", flag: "🇬🇧", country: "United Kingdom" },
  // { code: "AUD", flag: "🇦🇺", country: "Australia" },
  // { code: "CHF", flag: "🇨🇭", country: "Switzerland" },
  // { code: "CNY", flag: "🇨🇳", country: "China" },
  // { code: "HKD", flag: "🇭🇰", country: "Hong Kong" },
  // { code: "NZD", flag: "🇳🇿", country: "New Zealand" },
  // { code: "SEK", flag: "🇸🇪", country: "Sweden" },
  // { code: "KRW", flag: "🇰🇷", country: "South Korea" },
  // { code: "SGD", flag: "🇸🇬", country: "Singapore" },
  // { code: "NOK", flag: "🇳🇴", country: "Norway" },
  // { code: "MXN", flag: "🇲🇽", country: "Mexico" },
  // { code: "INR", flag: "🇮🇳", country: "India" },
  // { code: "RUB", flag: "🇷🇺", country: "Russia" },
  // { code: "ZAR", flag: "🇿🇦", country: "South Africa" },
  // { code: "TRY", flag: "🇹🇷", country: "Turkey" },
  // { code: "BRL", flag: "🇧🇷", country: "Brazil" },
  // { code: "AED", flag: "🇦🇪", country: "United Arab Emirates" },
  // { code: "ARS", flag: "🇦🇷", country: "Argentina" },
  // { code: "BGN", flag: "🇧🇬", country: "Bulgaria" },
  // { code: "CLP", flag: "🇨🇱", country: "Chile" },
  // { code: "COP", flag: "🇨🇴", country: "Colombia" },
  // { code: "CZK", flag: "🇨🇿", country: "Czech Republic" },
  // { code: "DKK", flag: "🇩🇰", country: "Denmark" },
  // { code: "EGP", flag: "🇪🇬", country: "Egypt" },
  // { code: "HUF", flag: "🇭🇺", country: "Hungary" },
  // { code: "IDR", flag: "🇮🇩", country: "Indonesia" },
  // { code: "ILS", flag: "🇮🇱", country: "Israel" },
];
